// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package products

type Product struct {
	Upc    string  `json:"upc"`
	Name   *string `json:"name,omitempty"`
	Price  *int    `json:"price,omitempty"`
	Weight *int    `json:"weight,omitempty"`
}

func (Product) IsEntity() {}
